

def test_delete_user(local_server_ctrl, auth_header, get_new_random_user_for_deleting, get_new_random_user):

    raise AssertionError

    local_server_ctrl.delete_user(get_new_random_user_for_deleting['id'], auth_data=auth_header)
